# Debug values
DEBUG_SHOW_FPS = True

# States
GAME_STATE_GALAXY = 1
GAME_STATE_SOLAR_SYSTEM = 2

# GUI states
GUI_STATE_GALAXY = 1
GUI_STATE_SOLAR_SYSTEM = 2

# Z vals
Z_BACKGROUND = 1000
Z_GUI = -500
Z_GUI_CONTAINERS = -550
Z_GUI_OBJECT_LEVEL_1 = -560
Z_GUI_OBJECT_LEVEL_2 = -570
Z_PLAYER_SHIP = -575
Z_GUI_OBJECT_LEVEL_3 = -580
Z_GUI_OBJECT_LEVEL_4 = -590
Z_GUI_OBJECT_LEVEL_5 = -600
Z_GUI_OBJECT_LEVEL_6 = -610
Z_GUI_OBJECT_LEVEL_7 = -620
Z_GUI_OBJECT_LEVEL_8 = -630
Z_GUI_OBJECT_LEVEL_9 = -640
Z_GUI_OBJECT_LEVEL_10 = -650
Z_MOUSE = -1000

# Process priorities
PRIORITY_MAIN_GAME = 1000
PRIORITY_GUI_ELEMENTS = 900
PRIORITY_GUI = 800

# Actions
ACTION_BUY_CREW = 1
ACTION_BUY_FUEL = 2
ACTION_MINE = 3
ACTION_MINE_GAS = 4
ACTION_SURVEY_ALPHA_CENTAURI_I = 5
ACTION_SURVEY_ALPHA_CENTAURI_II = 6
ACTION_SURVEY_ALPHA_CENTAURI_III = 7
ACTION_SURVEY_BERNARD_I = 8
ACTION_SURVEY_LALANDE_21185_II = 9
ACTION_SURVEY_SIRIUS_I = 10
ACTION_SURVEY_LUYTEN_726_8_I = 11
ACTION_SURVEY_EPSILON_ERIDANI_I = 12
ACTION_SURVEY_EZ_AQUARII_II = 13
ACTION_SURVEY_PROCYON_II = 14
ACTION_SURVEY_KRUGER_60_I = 15
ACTION_SURVEY_STRUVE_2399_I = 16

# Results when we go home
RESULT_SOLD_RESOURCES = 1
RESULT_ALPHA_CENTAURI_II = 2
RESULT_BERNARD_I = 3
RESULT_SIRIUS_I = 4
RESULT_LUYTEN_726_8_I = 5
RESULT_EZ_AQUARII_II = 6
RESULT_STRUVE_2399_I = 7

# Other consts
MAX_CREW = 10
FUEL_COST_TO_LAUNCH = 2
